version: '3'
services:
    maha-todoapp:
      image: syedamaha/maha-todoapp:2
      ports:
        - "3000:3000"
      depends_on:
        - "maha-couchdb"
      links:
        - "maha-couchdb"
      environment:
        - DATABASE_IP=172.17.0.1
    maha-couchdb:
      container_name: maha-couchdb
      image: syedamaha/maha-couchdb:2
      ports:
      - "5984:5984"
      - "5986:5986"
      environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
